name: torch
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - argon2_cffi=19.1.0=py36h7b6447c_0
  - bcrypt=3.1.6=py36h7b6447c_0
  - cffi=1.12.3=py36h2e261b9_0
  - colour=0.1.5=py36_0
  - cryptography=2.7=py36h1ba5d50_0
  - cudatoolkit=9.2=0
  - cx_oracle=7.0.0=py36h7b6447c_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - furl=2.0.0=py36_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - infinity=1.4=py36_0
  - intel-openmp=2019.3=199
  - intervals=0.8.1=py36_0
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10.1=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - lazy-object-proxy=1.4.2=py36h7b6447c_0
  - libedit=3.1.20181209=hc058e9b_0
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.1=py36h5429711_0
  - mccabe=0.6.1=py36_1
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.16.1=py36h7e9f1db_1
  - numpy-base=1.16.1=py36hde5b4d6_1
  - olefile=0.46=py36_0
  - orderedmultidict=1.0.1=py36_0
  - passlib=1.7.1=py36h28b3542_0
  - pcre=8.43=he6710b0_0
  - phonenumbers=8.10.15=py_0
  - pillow=6.1.0=py36h34e0f95_0
  - pycodestyle=2.5.0=py36_0
  - pycparser=2.19=py36_0
  - pyflakes=2.1.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlalchemy=1.3.7=py36h7b6447c_0
  - sqlalchemy-utils=0.33.11=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py36h7b6447c_0
  - typed-ast=1.3.4=py36h7b6447c_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - _libgcc_mutex=0.1=main
  - anyjson=0.3.3=py36_1
  - arrow=0.13.1=py36_0
  - asn1crypto=0.24.0=py36_0
  - astroid=2.2.5=py36_0
  - autopep8=1.4.4=py_0
  - av=7.0.1=py36h66a6ed3_1
  - babel=2.7.0=py_0
  - bzip2=1.0.8=h516909a_2
  - click=7.1.1=pyh8c360ce_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.8.1=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - ffmpeg=4.1.3=h167e202_0
  - flake8=3.7.9=py36_0
  - flask=1.1.1=py_0
  - fsspec=0.6.1=py_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - idna=2.9=py_1
  - isort=4.3.21=py36_0
  - lame=3.100=h14c3975_1001
  - libiconv=1.15=h516909a_1006
  - locket=0.2.0=py_2
  - msgpack-python=0.6.2=py36hc9558a2_0
  - nettle=3.4.1=h1bed415_1002
  - openh264=1.8.0=hdbcaa40_1000
  - packaging=19.2=py_0
  - partd=1.0.0=py_0
  - pip=19.1.1=py36_0
  - pylint=2.3.1=py36_0
  - pyparsing=2.4.0=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.1=py_0
  - setuptools=46.1.3=py36h9f0ad1d_0
  - sortedcontainers=2.1.0=py_0
  - tblib=1.4.0=py_0
  - toolz=0.10.0=py_0
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - x264=1!152.20180806=h14c3975_0
  - yaml=0.2.2=h516909a_1
  - _r-mutex=1.0.0=anacondar_1
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bwidget=1.9.11=1
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_0
  - curl=7.67.0=hbc83047_0
  - fribidi=1.0.5=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.4=h14c3975_4
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.67.0=h20c2e04_0
  - libffi=3.2.1=hd88cf55_4
  - libssh2=1.9.0=h1ba5d50_1
  - make=4.2.1=h1bed415_1
  - openssl=1.1.1d=h7b6447c_3
  - pango=1.42.4=h049681c_0
  - pixman=0.38.0=h7b6447c_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=h9bb98a2_1
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-bit=1.1_14=r36h96ca727_0
  - r-bit64=0.9_7=r36h96ca727_0
  - r-blob=1.1.1=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-memoise=1.1.0=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-rsqlite=2.1.1=r36h29659fb_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-utf8=1.1.4=r36h96ca727_0
  - scikit-learn=0.21.1=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - tktable=2.10=h14c3975_0
  - cuda90=1.0=h6433d27_0
  - pytorch=1.4.0=py3.6_cuda9.2.148_cudnn7.6.3_0
  - torchvision=0.5.0=py36_cu92
  - pip:
    - absl-py==0.7.1
    - aiohttp==3.6.2
    - appdirs==1.4.3
    - astor==0.8.0
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==19.1.0
    - backcall==0.1.0
    - backports.weakref==1.0rc1
    - beautifulsoup4==4.8.1
    - black==19.3b0
    - bleach==1.5.0
    - cachetools==3.1.1
    - chardet==3.0.4
    - cloudpickle==1.2.1
    - configparser==4.0.2
    - cython==0.29.14
    - dask==1.2.2
    - dask-kubernetes==0.8.0
    - dask-searchcv==0.2.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - dicom==0.9.9.post1
    - dill==0.3.1.1
    - distributed==1.28.1
    - enum34==1.1.6
    - et-xmlfile==1.0.1
    - future==0.18.2
    - gast==0.2.2
    - geojson==2.5.0
    - google-auth==1.6.3
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - googledrivefiledownloader==0.0.3
    - grpcio==1.29.0
    - heapdict==1.0.0
    - html5lib==0.9999999
    - idna-ssl==1.1.0
    - imageio==2.5.0
    - imbalanced-learn==0.5.0
    - imutils==0.5.3
    - ipdb==0.12
    - ipykernel==5.1.0
    - ipython==7.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jdcal==1.4.1
    - jedi==0.13.3
    - jsonpatch==1.24
    - jsonpointer==2.0
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - jupyter-server-proxy==1.2.0
    - kubernetes==9.0.0
    - littleutils==0.2.2
    - lxml==4.5.0
    - markdown==3.1.1
    - matplotlib-venn==0.11.5
    - mistune==0.8.4
    - mpld3==0.3
    - msgpack==0.6.1
    - multidict==4.6.1
    - multiprocess==0.70.9
    - natsort==6.0.0
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - networkx==2.3
    - nose==1.3.7
    - notebook==5.7.8
    - numexpr==2.7.1
    - oauthlib==3.0.1
    - opencv-python==4.2.0.32
    - openpyxl==3.0.1
    - outdated==0.2.0
    - p-tqdm==1.2
    - pandas==0.25.3
    - pandas-flavor==0.2.0
    - pandocfilters==1.4.2
    - parso==0.4.0
    - pathos==0.2.5
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pingouin==0.3.3
    - pixiedust==1.1.18
    - pox==0.2.7
    - ppft==1.6.6.1
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - protobuf==3.8.0
    - psutil==5.6.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.5
    - pydicom==1.3.0
    - pygments==2.3.1
    - pynrrd==0.4.0
    - pyrsistent==0.14.11
    - pytorch-lightning==0.7.6
    - pytorch-warmup==0.0.4
    - pywavelets==1.0.3
    - pyyaml==5.1.1
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - ranger==0.1.dev0
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - rsa==4.0
    - scikit-image==0.15.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simpervisor==0.3
    - simpleitk==1.2.4
    - skorch==0.5.0.post0
    - soupsieve==1.9.5
    - statsmodels==0.10.0
    - tables==3.6.1
    - tabulate==0.8.3
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - toml==0.10.0
    - torch==1.4.0
    - torch-encoding==1.0.1
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - tqdm==4.46.0
    - traitlets==4.3.2
    - typing-extensions==3.7.4.1
    - urllib3==1.25.3
    - visdom==0.1.8.9
    - visualdl==1.3.0
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - widgetsnbextension==3.4.2
    - xarray==0.15.1
    - xlrd==1.2.0
    - yarl==1.4.1
    - zict==0.1.4
prefix: /opt/conda/envs/torch

